In [1]:
import pandas as pd
import numpy as np

import itertools
# import time
# import statsmodels.api as sm
import matplotlib.pyplot as plt

# 6.5.1 Subset Selection

In [2]:
df = pd.read_csv('Hitters.csv')
df.head()

df.dropna(inplace=True)
len(df)

df.head()

,Player,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,...,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
1,-Alan Ashby,315,81,7,24,38,39,14,3449,835,...,321,414,375,N,W,632,43,10,475.0,N
2,-Alvin Davis,479,130,18,66,72,76,3,1624,457,...,224,266,263,A,W,880,82,14,480.0,A
3,-Andre Dawson,496,141,20,65,78,37,11,5628,1575,...,828,838,354,N,E,200,11,3,500.0,N
4,-Andres Galarraga,321,87,10,39,42,30,2,396,101,...,48,46,33,N,E,805,40,4,91.5,N
5,-Alfredo Griffin,594,169,4,74,51,35,11,4408,1133,...,501,336,194,A,W,282,421,25,750.0,A

In [3]:
dummies = pd.get_dummies(df[['League', 'Division', 'NewLeague']])

y = df.Salary

# Drop the column with the independent variable (Salary), and columns for which we created dummy variables
X_ = df.drop(['Player', 'Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')

# Define the feature set X.
X = pd.concat([X_, dummies[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)

In [4]:
X

,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,CHmRun,CRuns,CRBI,CWalks,PutOuts,Assists,Errors,League_N,Division_W,NewLeague_N
1,315.0,81.0,7.0,24.0,38.0,39.0,14.0,3449.0,835.0,69.0,321.0,414.0,375.0,632.0,43.0,10.0,1,1,1
2,479.0,130.0,18.0,66.0,72.0,76.0,3.0,1624.0,457.0,63.0,224.0,266.0,263.0,880.0,82.0,14.0,0,1,0
3,496.0,141.0,20.0,65.0,78.0,37.0,11.0,5628.0,1575.0,225.0,828.0,838.0,354.0,200.0,11.0,3.0,1,0,1
4,321.0,87.0,10.0,39.0,42.0,30.0,2.0,396.0,101.0,12.0,48.0,46.0,33.0,805.0,40.0,4.0,1,0,1
5,594.0,169.0,4.0,74.0,51.0,35.0,11.0,4408.0,1133.0,19.0,501.0,336.0,194.0,282.0,421.0,25.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,497.0,127.0,7.0,65.0,48.0,37.0,5.0,2703.0,806.0,32.0,379.0,311.0,138.0,325.0,9.0,3.0,1,0,1
318,492.0,136.0,5.0,76.0,50.0,94.0,12.0,5511.0,1511.0,39.0,897.0,451.0,875.0,313.0,381.0,20.0,0,0,0
319,475.0,126.0,3.0,61.0,43.0,52.0,6.0,1700.0,433.0,7.0,217.0,93.0,146.0,37.0,113.0,7.0,0,1,0
320,573.0,144.0,9.0,85.0,60.0,78.0,8.0,3198.0,857.0,97.0,470.0,420.0,332.0,1314.0,131.0,12.0,0,0,0
321,631.0,170.0,9.0,77.0,44.0,31.0,11.0,4908.0,1457.0,30.0,775.0,357.0,249.0,408.0,4.0,3.0,0,1,0

use `combinations` from `itertools`

In [5]:
for it in itertools.combinations(X.columns, 2):
    print(it)

('AtBat', 'Hits')
('AtBat', 'HmRun')
('AtBat', 'Runs')
('AtBat', 'RBI')
('AtBat', 'Walks')
('AtBat', 'Years')
('AtBat', 'CAtBat')
('AtBat', 'CHits')
('AtBat', 'CHmRun')
('AtBat', 'CRuns')
('AtBat', 'CRBI')
('AtBat', 'CWalks')
('AtBat', 'PutOuts')
('AtBat', 'Assists')
('AtBat', 'Errors')
('AtBat', 'League_N')
('AtBat', 'Division_W')
('AtBat', 'NewLeague_N')
('Hits', 'HmRun')
('Hits', 'Runs')
('Hits', 'RBI')
('Hits', 'Walks')
('Hits', 'Years')
('Hits', 'CAtBat')
('Hits', 'CHits')
('Hits', 'CHmRun')
('Hits', 'CRuns')
('Hits', 'CRBI')
('Hits', 'CWalks')
('Hits', 'PutOuts')
('Hits', 'Assists')
('Hits', 'Errors')
('Hits', 'League_N')
('Hits', 'Division_W')
('Hits', 'NewLeague_N')
('HmRun', 'Runs')
('HmRun', 'RBI')
('HmRun', 'Walks')
('HmRun', 'Years')
('HmRun', 'CAtBat')
('HmRun', 'CHits')
('HmRun', 'CHmRun')
('HmRun', 'CRuns')
('HmRun', 'CRBI')
('HmRun', 'CWalks')
('HmRun', 'PutOuts')
('HmRun', 'Assists')
('HmRun', 'Errors')
('HmRun', 'League_N')
('HmRun', 'Division_W')
('HmRun', 'NewLeague_N')
('Runs', 'RBI')
('Runs', 'Walks')
('Runs', 'Years')
('Runs', 'CAtBat')
('Runs', 'CHits')
('Runs', 'CHmRun')
('Runs', 'CRuns')
('Runs', 'CRBI')
('Runs', 'CWalks')
('Runs', 'PutOuts')
('Runs', 'Assists')
('Runs', 'Errors')
('Runs', 'League_N')
('Runs', 'Division_W')
('Runs', 'NewLeague_N')
('RBI', 'Walks')
('RBI', 'Years')
('RBI', 'CAtBat')
('RBI', 'CHits')
('RBI', 'CHmRun')
('RBI', 'CRuns')
('RBI', 'CRBI')
('RBI', 'CWalks')
('RBI', 'PutOuts')
('RBI', 'Assists')
('RBI', 'Errors')
('RBI', 'League_N')
('RBI', 'Division_W')
('RBI', 'NewLeague_N')
('Walks', 'Years')
('Walks', 'CAtBat')
('Walks', 'CHits')
('Walks', 'CHmRun')
('Walks', 'CRuns')
('Walks', 'CRBI')
('Walks', 'CWalks')
('Walks', 'PutOuts')
('Walks', 'Assists')
('Walks', 'Errors')
('Walks', 'League_N')
('Walks', 'Division_W')
('Walks', 'NewLeague_N')
('Years', 'CAtBat')
('Years', 'CHits')
('Years', 'CHmRun')
('Years', 'CRuns')
('Years', 'CRBI')
('Years', 'CWalks')
('Years', 'PutOuts')
('Years', 'Assists')
('Years', 'Errors')
('Years', 'League_N')
('Years', 'Division_W')
('Years', 'NewLeague_N')
('CAtBat', 'CHits')
('CAtBat', 'CHmRun')
('CAtBat', 'CRuns')
('CAtBat', 'CRBI')
('CAtBat', 'CWalks')
('CAtBat', 'PutOuts')
('CAtBat', 'Assists')
('CAtBat', 'Errors')
('CAtBat', 'League_N')
('CAtBat', 'Division_W')
('CAtBat', 'NewLeague_N')
('CHits', 'CHmRun')
('CHits', 'CRuns')
('CHits', 'CRBI')
('CHits', 'CWalks')
('CHits', 'PutOuts')
('CHits', 'Assists')
('CHits', 'Errors')
('CHits', 'League_N')
('CHits', 'Division_W')
('CHits', 'NewLeague_N')
('CHmRun', 'CRuns')
('CHmRun', 'CRBI')
('CHmRun', 'CWalks')
('CHmRun', 'PutOuts')
('CHmRun', 'Assists')
('CHmRun', 'Errors')
('CHmRun', 'League_N')
('CHmRun', 'Division_W')
('CHmRun', 'NewLeague_N')
('CRuns', 'CRBI')
('CRuns', 'CWalks')
('CRuns', 'PutOuts')
('CRuns', 'Assists')
('CRuns', 'Errors')
('CRuns', 'League_N')
('CRuns', 'Division_W')
('CRuns', 'NewLeague_N')
('CRBI', 'CWalks')
('CRBI', 'PutOuts')
('CRBI', 'Assists')
('CRBI', 'Errors')
('CRBI', 'League_N')
('CRBI', 'Division_W')
('CRBI', 'NewLeague_N')
('CWalks', 'PutOuts')
('CWalks', 'Assists')
('CWalks', 'Errors')
('CWalks', 'League_N')
('CWalks', 'Division_W')
('CWalks', 'NewLeague_N')
('PutOuts', 'Assists')
('PutOuts', 'Errors')
('PutOuts', 'League_N')
('PutOuts', 'Division_W')
('PutOuts', 'NewLeague_N')
('Assists', 'Errors')
('Assists', 'League_N')
('Assists', 'Division_W')
('Assists', 'NewLeague_N')
('Errors', 'League_N')
('Errors', 'Division_W')
('Errors', 'NewLeague_N')
('League_N', 'Division_W')
('League_N', 'NewLeague_N')
('Division_W', 'NewLeague_N')

In [6]:
import itertools
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

def best_subset_selection(X, y, k, var_names=None):
    if var_names is None:
        var_names = X.columns.tolist()
    
    best_model = None
    best_subset = None
    best_mse = float('inf')

    for subset in itertools.combinations(var_names, k):
        model = LinearRegression().fit(X[list(subset)], y)

        mse = mean_squared_error(y, model.predict(X[list(subset)]))

        if mse < best_mse:
            best_mse = mse
            best_model = model
            best_subset = subset
                
    return best_model, best_subset, best_mse

In [7]:
# find best subset with 1 predictor
best_subset_selection(X, y, 1)

(LinearRegression(), ('CRBI',), 137565.32036137575)

In [8]:
# find best subset with 2 predictors
best_subset_selection(X, y, 2)

(LinearRegression(), ('Hits', 'CRBI'), 116526.84368963054)

In [9]:
# find best subset with 3 predictors
best_subset_selection(X, y, 3)

(LinearRegression(), ('Hits', 'CRBI', 'PutOuts'), 111214.05648618752)

In [10]:
# find best subset with 7 predictors
best_subset_selection(X, y, 7)

(LinearRegression(),
 ('Hits', 'Walks', 'CAtBat', 'CHits', 'CHmRun', 'PutOuts', 'Division_W'),
 98503.9828921055)

## Forward Stepwise Selection

In [14]:
def find_next_best_predictor(X, y, best_subset, candidates):

    best_mse = float('inf')
    
    for candidate in candidates:
        model = LinearRegression().fit(X[best_subset+[candidate]], y)
        
        mse = mean_squared_error(y, model.predict(X[best_subset+[candidate]]))
        
        if mse < best_mse:
            best_mse = mse
            next_best = candidate

    return next_best

In [15]:
find_next_best_predictor(X, y, [], X.columns)

'CRBI'

In [16]:
find_next_best_predictor(X, y, ['CRBI'], ['Hits', 'Walks', 'CAtBat'])

'Hits'

In [17]:
def forward_stepwise_selection(X, y, k):
    var_names = X.columns.tolist()

    
    best_subset = []
    candidates = X.columns.tolist()

    
    best_model = None
    best_mse = float('inf')

    for i in range(k):
        next_best = find_next_best_predictor(X, y, best_subset, candidates)
        print(candidates, '->', next_best)
        
        best_subset.append(next_best)
        candidates.remove(next_best)
        
    return best_subset

forward_stepwise_selection(X, y, 7)

['AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W', 'NewLeague_N'] -> CRBI
['AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W', 'NewLeague_N'] -> Hits
['AtBat', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W', 'NewLeague_N'] -> PutOuts
['AtBat', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CWalks', 'Assists', 'Errors', 'League_N', 'Division_W', 'NewLeague_N'] -> Division_W
['AtBat', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CWalks', 'Assists', 'Errors', 'League_N', 'NewLeague_N'] -> AtBat
['HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CWalks', 'Assists', 'Errors', 'League_N', 'NewLeague_N'] -> Walks
['HmRun', 'Runs', 'RBI', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CWalks', 'Assists', 'Errors', 'League_N', 'NewLeague_N'] -> CWalks

['CRBI', 'Hits', 'PutOuts', 'Division_W', 'AtBat', 'Walks', 'CWalks']

## Backward stepwise selection

In [18]:
def find_worst_predictor(X, y, best_subset):

    best_mse = float('inf')
    
    for candidate in best_subset:
        
        predictors = [var for var in best_subset if var != candidate]
        model = LinearRegression().fit(X[predictors], y)
        
        mse = mean_squared_error(y, model.predict(X[predictors]))
        
        if mse < best_mse:
            best_mse = mse
            worst_predictor = candidate

    return worst_predictor

find_worst_predictor(X, y, ['CRBI', 'Hits', 'PutOuts', 'Division_W', 'AtBat', 'Walks', 'CWalks'])

'CWalks'

In [19]:
def backward_stepwise_selection(X, y, k):
    best_subset = X.columns.tolist()  # start from the full model

    for i in range(len(best_subset) - k):
        worst_predictor = find_worst_predictor(X, y, best_subset)
        print(best_subset, '->', worst_predictor)
        
        best_subset.remove(worst_predictor)
        
    return best_subset

In [20]:
backward_stepwise_selection(X, y, 7)

['AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W', 'NewLeague_N'] -> CHmRun
['AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years', 'CAtBat', 'CHits', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W', 'NewLeague_N'] -> Years
['AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'CAtBat', 'CHits', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W', 'NewLeague_N'] -> NewLeague_N
['AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'CAtBat', 'CHits', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W'] -> RBI
['AtBat', 'Hits', 'HmRun', 'Runs', 'Walks', 'CAtBat', 'CHits', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W'] -> CHits
['AtBat', 'Hits', 'HmRun', 'Runs', 'Walks', 'CAtBat', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W'] -> HmRun
['AtBat', 'Hits', 'Runs', 'Walks', 'CAtBat', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Errors', 'League_N', 'Division_W'] -> Errors
['AtBat', 'Hits', 'Runs', 'Walks', 'CAtBat', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'League_N', 'Division_W'] -> Runs
['AtBat', 'Hits', 'Walks', 'CAtBat', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'League_N', 'Division_W'] -> League_N
['AtBat', 'Hits', 'Walks', 'CAtBat', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Assists', 'Division_W'] -> Assists
['AtBat', 'Hits', 'Walks', 'CAtBat', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Division_W'] -> CAtBat
['AtBat', 'Hits', 'Walks', 'CRuns', 'CRBI', 'CWalks', 'PutOuts', 'Division_W'] -> CRBI

['AtBat', 'Hits', 'Walks', 'CRuns', 'CWalks', 'PutOuts', 'Division_W']